import { CountryCode } from "./country";
export declare const DEFAULT_CHECK_DIGIT = "00";
export declare function calculateCheckDigit(iban: string): string;
export declare function validate(iban: string): void;
export declare function validateCheckDigit(iban: string): void;
export declare function validateBban(countryCode: string, bban: string): void;
export declare function isSupportedCountry(countryCode: CountryCode): boolean;
export declare function getIbanLength(countryCode: CountryCode): number;
export declare function getCheckDigit(iban: string): string;
export declare function getCountryCode(iban: string): string;
export declare function getCountryCodeAndCheckDigit(iban: string): string;
export declare function getBban(iban: string): string;
export declare function getAccountNumber(iban: string): string | null;
export declare function getBankCode(iban: string): string | null;
export declare function getBranchCode(iban: string): string | null;
export declare function getNationalCheckDigit(iban: string): string | null;
export declare function getBranchCheckDigit(iban: string): string | null;
export declare function getCurrencyType(iban: string): string | null;
export declare function getAccountType(iban: string): string | null;
export declare function getOwnerAccountType(iban: string): string | null;
export declare function getIdentificationNumber(iban: string): string | null;
export declare function replaceCheckDigit(iban: string, checkDigit: string): string;
export declare function toFormattedString(iban: string, separator?: string): string;
export declare function toFormattedStringBBAN(iban: string, separator?: string): string;
export declare function validateCheckDigitChecksum(iban: string): void;
